create table balance (
  account     integer primary key,
  type        char not null,
  description varchar(1000)
);

create sequence accaunt_id_sequence
  start with 0
  increment by 1;

create sequence activ_accaunt_sequence
  start with 1
  increment by 1;

create sequence pasiv_accaunt_sequence
  start with 0
  increment by 1;

create table account (
  id              integer generated by default as sequence accaunt_id_sequence primary key,
  balance_account integer,
  account         integer,
  amount          double,
  unique (balance_account, account)
);

create sequence document_sequence
  start with 0
  increment by 1;

